### ISSUE TITLE
standard update

### ISSUE THREAD

**Issue by HughP** [wooorm/iso-639-3#1]
The ISO 639-3 standard is updated "periodically" (usually annually) how do you manage updates to your package? do you indicate which version of the standard you are using?

**Comment by wooorm** [comment]
The source is crawled from the spec; I do not indicate which version is used, but it can be inferred from the timestamp of the published version.

Are you saying this project is out of date?

**Comment by wooorm** [comment]
@HughP Ping!

**Comment by HughP** [comment]
Yes, I am saying that the 2015 changes have been released (15 Jan 2016) and by looking at the commit date I would infer that your project has only included the 2014 changes. It would be helpful if the date of the last update included would be included in the Readme.md.
