### ISSUE TITLE
Creating a unique exit point

### ISSUE THREAD

**Issue by claudenirmf** [wooorm/iso-639-3#7]
Hi, thanks for developing this project =)

Why don't you have an `index.js` file to centralize all require statements? Is that a choice or is it OK if I PR this modification?

**Comment by wooorm** [comment]
Hi @claudenirmf! thanks for your patience and kind words!

The data in this project is pretty big! 75kb minzipped. The reason for adding those other files was for folks to not have to load the whole file, but instead loading just the tiny part they need. Thus, adding them all together kinda defeats the purpose of them: it creates an even bigger file.

Now, if you have the whole, you could also the other indexes in your code? [Like this](https://github.com/wooorm/iso-639-3/blob/59b9700e0bb135db2443b29b11d5391c4945f663/build.js#L89-L102)?

**Comment by claudenirmf** [comment]
Cool, I think I got it. 

My use case is that I need to map language codes both ways between 639-3 and 639-1, so I already to that. But as my application is on the server, not the browser, size is not really a concern. 

I see value on having this mapping feature in the package rather than writing it on my own project, but I understand if you are concerned with a different use case.

**Comment by wooorm** [comment]
> application is on the server, not the browser, size is not really a concern.

Not really, but it’s still 1mb to import the whole thing, which isn’t too bad but slows startup time a bit, and still adds some weight when expanded into memory. And it would be more if we’re adding all these indexes!

> I see value on having this mapping feature in the package rather than writing it on my own project

Agreed, hence why these are available and published, but at separate paths.
Reading your last comment, is it correct that you’d need a 1 to 3 mapping too? Or is the current main file and some code internally enough for you?

**Comment by claudenirmf** [comment]
> Reading your last comment, is it correct that you’d need a 1 to 3 mapping too? Or is the current main file and some code internally enough for you?

I have to transform requests referring to 639-3 to 639-1 and transform field names on 639-1 to 639-3 on the way back (dataset and API using different standards). What I do is to build the "reverse map" for my project, consult the map during runtime, and cache the results (people only need 5 to 10 language codes at the end of the day).

> Not really, but it’s still 1mb to import the whole thing, which isn’t too bad but slows startup time a bit, and still adds some weight when expanded into memory. And it would be more if we’re adding all these indexes!

I will reflect on your comments and check my code's efficiency. Thanks =)

Maybe we can close this issue.

**Comment by wooorm** [comment]
Alright, I’ll close this. Do let me know if an index for 1 -> 3 should be added.
