### ISSUE TITLE
Adding a local field to the language object [feature request]

### ISSUE THREAD

**Issue by Oktogazh** [wooorm/iso-639-3#8]
Does the adding of a `local` field, with the translation of the name of the language in the language itself would be problematic?
Optionally with with a `dir`field like so:
```
  {
    name: 'Arabic',
    local: 'اَلْعَرَبِيَّةُ',
    dir: 'rtl',
    type: 'living',
    scope: 'macrolanguage',
    iso6393: 'ara',
    iso6392B: 'ara',
    iso6392T: 'ara',
    iso6391: 'ar'
  }
```
[This page](https://meta.wikimedia.org/wiki/Template:N_en/list) could be a good starting point, as it contains most of the written languages. Most 'smaller' languages don't have any local written version, just the latinized one used in the name field.
I have no idea how to programmatically add the aforementioned fields from the data of the page.

**Comment by wooorm** [comment]
Unfortunately that’s not something for this project.
This project’s goal is to expose the spec. All the data here, is what’s exposed by the spec.
Other data, while interesting, is not exposed.

There are specs for stuff like that though: Unicode CLDR! Most programming languages already have APIs for that. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames
